/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type Hacl_Curve25519_uint8_p = *mut u8;
extern "C" {
    pub fn Hacl_Curve25519_crypto_scalarmult(
        mypublic: *mut u8,
        secret: *mut u8,
        basepoint: *mut u8,
    );
}
