/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
extern "C" {
    pub fn hmac_core(mac: *mut u8, key: *mut u8, data: *mut u8, len: u32);
}
extern "C" {
    pub fn hmac(mac: *mut u8, key: *mut u8, keylen: u32, data: *mut u8, datalen: u32);
}
