/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
pub type __uint64_t = crate::libc::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Hacl_Impl_Poly1305_64_State_poly1305_state {
    pub r: *mut u64,
    pub h: *mut u64,
}
#[test]
fn bindgen_test_layout_Hacl_Impl_Poly1305_64_State_poly1305_state() {
    assert_eq!(
        ::core::mem::size_of::<Hacl_Impl_Poly1305_64_State_poly1305_state>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<Hacl_Impl_Poly1305_64_State_poly1305_state>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<Hacl_Impl_Poly1305_64_State_poly1305_state>())).r as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state),
            "::",
            stringify!(r)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<Hacl_Impl_Poly1305_64_State_poly1305_state>())).h as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state),
            "::",
            stringify!(h)
        )
    );
}
pub type Hacl_Poly1305_64_uint8_p = *mut u8;
pub type Hacl_Poly1305_64_uint64_t = u64;
pub type Hacl_Poly1305_64_key = *mut u8;
pub type Hacl_Poly1305_64_state = Hacl_Impl_Poly1305_64_State_poly1305_state;
extern "C" {
    pub fn Hacl_Poly1305_64_mk_state(
        r: *mut u64,
        acc: *mut u64,
    ) -> Hacl_Impl_Poly1305_64_State_poly1305_state;
}
extern "C" {
    pub fn Hacl_Poly1305_64_init(st: Hacl_Impl_Poly1305_64_State_poly1305_state, k1: *mut u8);
}
extern "C" {
    pub fn Hacl_Poly1305_64_update_block(
        st: Hacl_Impl_Poly1305_64_State_poly1305_state,
        m: *mut u8,
    );
}
extern "C" {
    pub fn Hacl_Poly1305_64_update(
        st: Hacl_Impl_Poly1305_64_State_poly1305_state,
        m: *mut u8,
        num_blocks: u32,
    );
}
extern "C" {
    pub fn Hacl_Poly1305_64_update_last(
        st: Hacl_Impl_Poly1305_64_State_poly1305_state,
        m: *mut u8,
        len1: u32,
    );
}
extern "C" {
    pub fn Hacl_Poly1305_64_finish(
        st: Hacl_Impl_Poly1305_64_State_poly1305_state,
        mac: *mut u8,
        k1: *mut u8,
    );
}
extern "C" {
    pub fn Hacl_Poly1305_64_crypto_onetimeauth(
        output: *mut u8,
        input: *mut u8,
        len1: u64,
        k1: *mut u8,
    );
}
