/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
pub type __uint64_t = crate::libc::c_ulong;
pub type Hacl_Salsa20_uint8_p = *mut u8;
pub type Hacl_Salsa20_uint32_t = u32;
pub type Hacl_Salsa20_state = *mut u32;
extern "C" {
    pub fn Hacl_Salsa20_salsa20(
        output: *mut u8,
        plain: *mut u8,
        len: u32,
        k: *mut u8,
        n1: *mut u8,
        ctr: u64,
    );
}
extern "C" {
    pub fn Hacl_Salsa20_hsalsa20(output: *mut u8, key: *mut u8, nonce: *mut u8);
}
