/* automatically generated by rust-bindgen */

pub type __uint8_t = crate::libc::c_uchar;
pub type __uint32_t = crate::libc::c_uint;
pub type __uint64_t = crate::libc::c_ulong;
pub type Hacl_SHA2_384_uint8_t = u8;
pub type Hacl_SHA2_384_uint32_t = u32;
pub type Hacl_SHA2_384_uint64_t = u64;
pub type Hacl_SHA2_384_uint8_ht = u8;
pub type Hacl_SHA2_384_uint64_ht = u64;
pub type Hacl_SHA2_384_uint64_p = *mut u64;
pub type Hacl_SHA2_384_uint8_p = *mut u8;
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_384_size_hash"]
    pub static mut Hacl_SHA2_384_size_hash: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_384_size_block"]
    pub static mut Hacl_SHA2_384_size_block: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_384_size_state"]
    pub static mut Hacl_SHA2_384_size_state: u32;
}
extern "C" {
    pub fn Hacl_SHA2_384_init(state: *mut u64);
}
extern "C" {
    pub fn Hacl_SHA2_384_update(state: *mut u64, data_8: *mut u8);
}
extern "C" {
    pub fn Hacl_SHA2_384_update_multi(state: *mut u64, data: *mut u8, n1: u32);
}
extern "C" {
    pub fn Hacl_SHA2_384_update_last(state: *mut u64, data: *mut u8, len: u64);
}
extern "C" {
    pub fn Hacl_SHA2_384_finish(state: *mut u64, hash1: *mut u8);
}
extern "C" {
    pub fn Hacl_SHA2_384_hash(hash1: *mut u8, input: *mut u8, len: u32);
}
