/* automatically generated by rust-bindgen */

pub type __uint8_t = ::libc::c_uchar;
pub type __int32_t = ::libc::c_int;
pub type __uint32_t = ::libc::c_uint;
pub type __uint64_t = ::libc::c_ulong;

pub type Prims_int = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Hacl_Impl_Poly1305_64_State_poly1305_state {
    pub r: *mut u64,
    pub h: *mut u64,
}
#[test]
fn bindgen_test_layout_Hacl_Impl_Poly1305_64_State_poly1305_state() {
    assert_eq!(
        ::core::mem::size_of::<Hacl_Impl_Poly1305_64_State_poly1305_state>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<Hacl_Impl_Poly1305_64_State_poly1305_state>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<Hacl_Impl_Poly1305_64_State_poly1305_state>())).r as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state),
            "::",
            stringify!(r)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<Hacl_Impl_Poly1305_64_State_poly1305_state>())).h as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Hacl_Impl_Poly1305_64_State_poly1305_state),
            "::",
            stringify!(h)
        )
    );
}
extern "C" {
    #[link_name = "\u{1}Hacl_Chacha20Poly1305_noncelen"]
    pub static mut Hacl_Chacha20Poly1305_noncelen: Prims_int;
}
extern "C" {
    #[link_name = "\u{1}Hacl_Chacha20Poly1305_keylen"]
    pub static mut Hacl_Chacha20Poly1305_keylen: Prims_int;
}
extern "C" {
    #[link_name = "\u{1}Hacl_Chacha20Poly1305_maclen"]
    pub static mut Hacl_Chacha20Poly1305_maclen: Prims_int;
}
pub type Hacl_Chacha20Poly1305_state = Hacl_Impl_Poly1305_64_State_poly1305_state;
pub type Hacl_Chacha20Poly1305_log_t = *mut ::libc::c_void;
extern "C" {
    pub fn Hacl_Chacha20Poly1305_encode_length(lb: *mut u8, aad_len: u32, mlen: u32);
}
extern "C" {
    pub fn Hacl_Chacha20Poly1305_aead_encrypt_(
        c: *mut u8,
        mac: *mut u8,
        m: *mut u8,
        mlen: u32,
        aad1: *mut u8,
        aadlen: u32,
        k1: *mut u8,
        n1: *mut u8,
    ) -> u32;
}
extern "C" {
    pub fn Hacl_Chacha20Poly1305_aead_encrypt(
        c: *mut u8,
        mac: *mut u8,
        m: *mut u8,
        mlen: u32,
        aad1: *mut u8,
        aadlen: u32,
        k1: *mut u8,
        n1: *mut u8,
    ) -> u32;
}
extern "C" {
    pub fn Hacl_Chacha20Poly1305_aead_decrypt(
        m: *mut u8,
        c: *mut u8,
        mlen: u32,
        mac: *mut u8,
        aad1: *mut u8,
        aadlen: u32,
        k1: *mut u8,
        n1: *mut u8,
    ) -> u32;
}
