/* automatically generated by rust-bindgen */

pub type __uint8_t = ::libc::c_uchar;
pub type __uint32_t = ::libc::c_uint;
pub type __uint64_t = ::libc::c_ulong;
pub type FStar_UInt128_t = [u64; 2];
extern "C" {
    pub fn Hacl_Policies_declassify_u8(x: u8) -> u8;
}
extern "C" {
    pub fn Hacl_Policies_declassify_u32(x: u32) -> u32;
}
extern "C" {
    pub fn Hacl_Policies_declassify_u64(x: u64) -> u64;
}
extern "C" {
    pub fn Hacl_Policies_declassify_u128(x: FStar_UInt128_t) -> FStar_UInt128_t;
}
extern "C" {
    pub fn Hacl_Policies_cmp_bytes_(b1: *mut u8, b2: *mut u8, len: u32, tmp: *mut u8) -> u8;
}
extern "C" {
    pub fn Hacl_Policies_cmp_bytes(b1: *mut u8, b2: *mut u8, len: u32) -> u8;
}
