/* automatically generated by rust-bindgen */

pub type __uint8_t = ::libc::c_uchar;
pub type __uint32_t = ::libc::c_uint;
pub type __uint64_t = ::libc::c_ulong;
pub type FStar_UInt128_t = [u64; 2];
pub type Hacl_SHA2_512_uint8_t = u8;
pub type Hacl_SHA2_512_uint32_t = u32;
pub type Hacl_SHA2_512_uint64_t = u64;
pub type Hacl_SHA2_512_uint8_ht = u8;
pub type Hacl_SHA2_512_uint32_ht = u32;
pub type Hacl_SHA2_512_uint64_ht = u64;
pub type Hacl_SHA2_512_uint128_ht = FStar_UInt128_t;
pub type Hacl_SHA2_512_uint64_p = *mut u64;
pub type Hacl_SHA2_512_uint8_p = *mut u8;
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_word"]
    pub static mut Hacl_SHA2_512_size_word: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_hash_w"]
    pub static mut Hacl_SHA2_512_size_hash_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_block_w"]
    pub static mut Hacl_SHA2_512_size_block_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_hash"]
    pub static mut Hacl_SHA2_512_size_hash: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_block"]
    pub static mut Hacl_SHA2_512_size_block: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_k_w"]
    pub static mut Hacl_SHA2_512_size_k_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_ws_w"]
    pub static mut Hacl_SHA2_512_size_ws_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_whash_w"]
    pub static mut Hacl_SHA2_512_size_whash_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_count_w"]
    pub static mut Hacl_SHA2_512_size_count_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_len_8"]
    pub static mut Hacl_SHA2_512_size_len_8: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_size_state"]
    pub static mut Hacl_SHA2_512_size_state: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_pos_k_w"]
    pub static mut Hacl_SHA2_512_pos_k_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_pos_ws_w"]
    pub static mut Hacl_SHA2_512_pos_ws_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_pos_whash_w"]
    pub static mut Hacl_SHA2_512_pos_whash_w: u32;
}
extern "C" {
    #[link_name = "\u{1}Hacl_SHA2_512_pos_count_w"]
    pub static mut Hacl_SHA2_512_pos_count_w: u32;
}
extern "C" {
    pub fn Hacl_SHA2_512_init(state: *mut u64);
}
extern "C" {
    pub fn Hacl_SHA2_512_update(state: *mut u64, data: *mut u8);
}
extern "C" {
    pub fn Hacl_SHA2_512_update_multi(state: *mut u64, data: *mut u8, n1: u32);
}
extern "C" {
    pub fn Hacl_SHA2_512_update_last(state: *mut u64, data: *mut u8, len: u64);
}
extern "C" {
    pub fn Hacl_SHA2_512_finish(state: *mut u64, hash1: *mut u8);
}
extern "C" {
    pub fn Hacl_SHA2_512_hash(hash1: *mut u8, input: *mut u8, len: u32);
}
